### PR TITLE
Align grid implementation closer to continuous space

### PR DESCRIPTION
**Pull request by Libbum**
The current `GridSpace` is quite crippled in comparison to the `ContinuousSpace` version. This attempts to align both versions through both input arguments and output ability (for example, allow `Real` values for marker size, allow functions&mdash;hence Shapes as well as Symbols&mdash;in marker type etc.)

Notes: 
- I haven't looked at `GraphSpace`, but I'm sure it needs some alignment as well.
- We'll need an associated PR in Agents.jl if this is merged, since you're no longer forced to get the first value in an array each time. (e.g. in Schelling: `groupcolor(a) = a[1].group == 1 ? :blue : :orange` can now just use `a.group`).

### CODE REVIEW

**Comment by Datseris** [comment]
Can you explain to me what you mean by "align"? :P

**Comment by Libbum** [comment]
"Make it closer to the implementation of ..."

- as = x -> 10 in grid, as = 8 in continuous
- am only Symbol in grid, am Symbol, String or Function in continuous

So this essentially makes them closer to the some thing, just for a different Space type.

**Comment by Datseris** [comment]
I am confused. So what is supposed to happen for grid space if there are several agents at the same grid point?

Maybe with your approach it is worth defining `offset` similarly with `as` etc., which returls an offset for each agent. We can use this then in the wolf model as :
```julia
offset(::Wolf) = (-0.1, 0)
offset(::Sheep) = (0.1, 0)
offset(::Gras) = (0, 0)
```

**Comment by Datseris** [comment]
We will then have to split the functionalities. and I agree, it makes sense that GridSpace plotting should be more similar to COntinuousSpace plotting.

GraphSpace should stay as is though, because it is clear from an application perspective that you will always have many (possiblity hundreds) of agents per node.

**Comment by Libbum** [comment]
This isn't a complete solution. As I said in slack, I essentially stopped going down this route mid way.
Any offset code we consider adding for multiple agents would be on top of this PR.

Here, I'm really allowing the possibility of `Shape` to be a marker type (with the capability of a `Function` call returning the `Shape`. With this, you can call `marker_type(agent) = ...`, which you can then leverage multiple dispatch if needed (manually adding in an offset if required).

**Pull request merged**
