### PR TITLE
rework plotabm, remove plot2D, unify interface

### PR DESCRIPTION
**Pull request by Datseris**
I think this PR provides a drastically simpler interface than the previous one.

### CODE REVIEW

**Comment by Datseris** [comment]
See the new Schelling example

**Review by kavir1698 — APPROVED** [review]

**Comment by Datseris** [comment]
ah LOL I now realize you can't see the updated examples HAHAHAHAHAHAH

**Comment by Datseris** [comment]
forest fire:
```julia
using AgentsPlots
forest = model_initiation()
step!(forest, dummystep, forest_step!, 1)
treecolor(a) = a[1].status == 1 ? :green : :red
plotabm(forest; ac = treecolor, ms = 5, msw=0)

# or animate it
cd(@__DIR__) #src
forest = model_initiation(f = 0.005)
anim = @animate for i in 1:20
    step!(forest, dummystep, forest_step!, 1)
    p1 = plotabm(forest; ac = treecolor, ms = 5, msw=0)
    title!(p1, "step $(i)")
end

gif(anim, "forest.gif", fps = 2);

```

forest

schelling:

```julia
using AgentsPlots
groupcolor(a) = a[1].group == 1 ? :blue : :orange
groupmarker(a) = a[1].group == 1 ? :circle : :square
plotabm(model; ac = groupcolor, am = groupmarker)

# ## Animating the evolution

# The function [`plotabm`](@ref) can be used to make your own animations
cd(@__DIR__) #src
model = initialize();
anim = @animate for i in 1:10
    step!(model, agent_step!, 1)
    p1 = plotabm(model; ac = groupcolor, am = groupmarker)
    title!(p1, "step $(i)")
end

gif(anim, "schelling.gif", fps = 2);

```

schelling

**Comment by Datseris** [comment]
So, do I merge?

**Comment by kavir1698** [comment]
Yes, It's great!

**Pull request merged**
